import { reactive } from 'vue'

export const store = reactive({
  area: 33,
	areas: [
    {id: 0, name: '北京'},
    {id: 1, name: '上海'},
    {id: 2, name: '天津'},
    {id: 3, name: '重庆'},
    {id: 4, name: '河北'},
    {id: 5, name: '河南'},
    {id: 6, name: '辽宁'},
    {id: 7, name: '吉林'},
    {id: 8, name: '黑龙江'},
    {id: 9, name: '内蒙古'},
    {id: 10, name: '江苏'},
    {id: 11, name: '山东'},
    {id: 12, name: '安徽'},
    {id: 13, name: '浙江'},
    {id: 14, name: '福建'},
    {id: 15, name: '湖北'},
    {id: 16, name: '湖南'},
    {id: 17, name: '广东'},
    {id: 18, name: '广西'},
    {id: 19, name: '江西'},
    {id: 20, name: '四川'},
    {id: 21, name: '海南'},
    {id: 22, name: '贵州'},
    {id: 23, name: '云南'},
    {id: 24, name: '西藏'},
    {id: 25, name: '陕西'},
    {id: 26, name: '甘肃'},
    {id: 27, name: '青海'},
    {id: 28, name: '宁夏'},
    {id: 29, name: '新疆'},
    {id: 30, name: '港澳'},
    {id: 31, name: '台湾'},
    {id: 32, name: '钓鱼岛'},
    {id: 33, name: '海外'}
  ]
})